name: Renovate

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Run Renovate via docker
        run: |
          docker run --rm \
            -e RENOVATE_PLATFORM=github \
            -e RENOVATE_TOKEN="${{ secrets.RENOVATE_TOKEN }}" \
            -e RENOVATE_REPOSITORIES="${{ github.repository }}" \
            -e LOG_LEVEL=debug \
            ghcr.io/renovatebot/renovate:latest
